version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
  backend:
    image: backend
    environment: 
      - PORT=3001
      - MONGODB_URI=mongodb://root:pass@mongodb:27017
      - IMPORT_DATA_PATH=./data
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    container_name: backend
    depends_on: 
      - mongodb
  frontend:
    image: frontend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    build:
      context: ./frontend
      dockerfile: ./Dockerfile 
    ports:
      - 3000:80
    container_name: frontend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend # wait for the frontend container to be started
      - backend
