describe('StationsView', () => {
  beforeEach(function() {
    cy.request('POST', 'http://localhost:3001/test/reset')
    cy.request('POST', 'http://localhost:3001/test/initState')
    cy.visit('http://localhost:3000/stations')
  })
  it('StationsView shows all stations from db', function() {
    cy.contains('Laajalahden aukio')
    cy.contains('94')
    cy.contains('Teljäntie')
    cy.contains('100')
    cy.contains('Töölöntulli')
    cy.contains('82')
    cy.contains('Pasilan asema')
    cy.contains('113')
    cy.contains('Näkinsilta')
    cy.contains('123')
    cy.contains('Vilhonvuorenkatu')
    cy.contains('121')
    cy.contains('Viiskulma')
    cy.contains('4')
    cy.contains('Hernesaarenranta')
    cy.contains('65')
    cy.contains('Koskelan varikko')
    cy.contains('292')
    cy.contains('Paavalinpuisto')
    cy.contains('133')
    cy.contains('Kansallismuseo')
    cy.contains('34')
    cy.contains('Stenbäckinkatu')
    cy.contains('81')
    cy.contains('Viikin normaalikoulu')
    cy.contains('240')
    cy.contains('Puotila (M)')
    cy.contains('281')
    cy.contains('Linnanmäki')
    cy.contains('116')
    cy.contains('Brahen puistikko')
    cy.contains('117')
    cy.contains('Pohjolankatu')
    cy.contains('145')
    cy.contains('Käpylän asema')
    cy.contains('147')
    cy.contains('Oulunkylän asema')
    cy.contains('232')
    cy.contains('Kalevankatu')
    cy.contains('69')
    cy.contains('Välimerenkatu')
    cy.contains('62')
    cy.contains('Jämeräntaival')
    cy.contains('547')
  })
})
